.classpath, src/main/java/nl/tudelft/scrumbledore/Level.java, src/main/java/nl/tudelft/scrumbledore/LevelElement.java, src/main/java/nl/tudelft/scrumbledore/Vector.java, src/test/java/nl/tudelft/scrumbledore/LevelElementTest.java, src/test/java/nl/tudelft/scrumbledore/VectorTest.java
Added some extra properties and methods to LevelElement and related classes. Added some Test Suites for these classes. Maven Test passes.
=> Level elements

src/main/java/nl/tudelft/scrumbledore/Scrumbledore.java, src/main/java/nl/tudelft/scrumbledore/ScrumbledoreGUI.java
This pull request contains the updates required to change the main class so that the GUI will now adhere to the model-view-controller scheme we wish to adhere to.  I discussed this with Jesse during class.
Also contains minor checkstyle and javadoc fixes needed.
=> Guimodelfix

src/main/java/nl/tudelft/scrumbledore/Fruit.java, src/main/java/nl/tudelft/scrumbledore/NPC.java, src/main/java/nl/tudelft/scrumbledore/Platform.java
Please check additions and merge on ack.
=> Added additional private variables and getters/setters < feature

src/main/java/nl/tudelft/scrumbledore/Collisions.java, src/main/java/nl/tudelft/scrumbledore/Game.java, src/main/java/nl/tudelft/scrumbledore/Kinetics.java, src/main/java/nl/tudelft/scrumbledore/Launcher.java, src/main/java/nl/tudelft/scrumbledore/StepTimer.java
Add very basic start of Launcher and StepTimer. Minor updates of dependency classes of these classes.
=> Launcher and StepTimer

src/main/java/nl/tudelft/scrumbledore/Vector.java, src/test/java/nl/tudelft/scrumbledore/VectorTest.java
Update for the Vector class and it's Test Suite. Allowing to scale Vectors and find the dot product.
=> Vector update

src/main/java/nl/tudelft/scrumbledore/Fruit.java, src/main/java/nl/tudelft/scrumbledore/Gravity.java, src/main/java/nl/tudelft/scrumbledore/Kinetics.java, src/main/java/nl/tudelft/scrumbledore/Level.java, src/main/java/nl/tudelft/scrumbledore/LevelParser.java, src/main/java/nl/tudelft/scrumbledore/NPC.java, src/main/java/nl/tudelft/scrumbledore/Platform.java, src/main/java/nl/tudelft/scrumbledore/Player.java, src/test/java/nl/tudelft/scrumbledore/GravityTest.java, src/test/java/nl/tudelft/scrumbledore/LevelParserTest.java, src/test/java/nl/tudelft/scrumbledore/LevelTest.java
Please merge on approval:
New way of obtaining level elements from level class:
getElements is now:
- getPlayer()
- getMovingElements()
- getPlatforms()
=> Seperate levelelements level

.classpath, src/main/java/nl/tudelft/scrumbledore/Constants.java, src/main/java/nl/tudelft/scrumbledore/ScrumbledoreGUI.java
Contains improvements to the GUI layout and organization, including but not limited to successfully implementing the refreshing canvas that will be utilized to display the game. Debug is contained as an example, so that we can work off of that.
As a side note, to remove the debug lines, simply remove the //TODO lines.
=> Guigamedisplay

src/main/java/nl/tudelft/scrumbledore/LevelParser.java, src/main/java/nl/tudelft/scrumbledore/Platform.java, src/test/java/nl/tudelft/scrumbledore/LevelParserTest.java
=> Level passable

src/main/java/nl/tudelft/scrumbledore/Game.java, src/main/java/nl/tudelft/scrumbledore/Gravity.java, src/main/java/nl/tudelft/scrumbledore/Kinetics.java, src/main/java/nl/tudelft/scrumbledore/StepTimer.java, src/main/java/nl/tudelft/scrumbledore/Vector.java, src/test/java/nl/tudelft/scrumbledore/GravityTest.java
The steptimer uses a variable rate and can be paused and unpaused.
=> Implemented the Steptimer.

src/main/java/nl/tudelft/scrumbledore/ScrumbledoreGUI.java, src/main/java/nl/tudelft/scrumbledore/style.css
Added some button functioning that had been removed with GUI debugging.  Added some basic CSS items, but commented out their functioning.  Want more time with them, but essential resource organization for it has been done.
=> Gui basicfunc style

src/main/java/nl/tudelft/scrumbledore/Constants.java, src/main/java/nl/tudelft/scrumbledore/LevelParser.java, src/main/java/nl/tudelft/scrumbledore/ScrumbledoreGUI.java, src/test/java/nl/tudelft/scrumbledore/LevelParserTest.java
Update LevelParser and its Test Suite to use doubles for coordinates in
Vectors. Update getMiddleOfBlock method to support any double for
blockSize. Update BlockSize constant to 32.
=> Add support for even sized grid cells.

src/main/java/nl/tudelft/scrumbledore/Kinetics.java
Implemented basic falling though holes functionality.
=> Fall through holes

src/main/java/nl/tudelft/scrumbledore/LevelParser.java, src/test/java/nl/tudelft/scrumbledore/LevelParserTest.java
Changed the x, y representation of a sprite to the upper left corner instead of its middle
=> Changed coordinates of sprite from mid x mid to 0 x 0

src/main/java/nl/tudelft/scrumbledore/CollisionsLevelModifier.java, src/main/java/nl/tudelft/scrumbledore/Game.java, src/main/java/nl/tudelft/scrumbledore/Level.java
Added a collision check that updates score when player hits fruit.
=> Score counting collisions

src/main/java/nl/tudelft/scrumbledore/BubbleActionLevelModifier.java, src/main/java/nl/tudelft/scrumbledore/CollisionsLevelModifier.java, src/main/java/nl/tudelft/scrumbledore/Constants.java, src/main/java/nl/tudelft/scrumbledore/GUI.java, src/main/java/nl/tudelft/scrumbledore/KineticsLevelModifier.java
First set of exception fixes that allows for the game to be run.
Index Out Of Bounds Exceptions are not yet fixed, but will in a future commit be addressed using a fire rate limit.
=> Fix exceptions

src/main/java/nl/tudelft/scrumbledore/CollisionsLevelModifier.java, src/main/java/nl/tudelft/scrumbledore/GUI.java, src/main/java/nl/tudelft/scrumbledore/Player.java
Please review changes and merge on approval
=> Fire rate limit

src/main/java/nl/tudelft/scrumbledore/Constants.java, src/main/java/nl/tudelft/scrumbledore/GUI.java, src/main/java/nl/tudelft/scrumbledore/Game.java
Removed the bug that caused the completion of the last level to throw an outofboundsexception, and replaced it with an animation halter and a dialog box.  Can be edited later to be cooler/go to a menu.
=> Fix level end

src/main/java/nl/tudelft/scrumbledore/CollisionsLevelModifier.java, src/main/java/nl/tudelft/scrumbledore/GUI.java, src/main/java/nl/tudelft/scrumbledore/Game.java, src/main/java/nl/tudelft/scrumbledore/Player.java
=> Player enemy collision

src/main/java/nl/tudelft/scrumbledore/GUI.java
Fix issue with checking if the player is still alive and subsequently restarting the game.
=> Fix player check alive.

src/main/java/nl/tudelft/scrumbledore/KineticsLevelModifier.java, src/main/java/nl/tudelft/scrumbledore/Level.java, src/test/java/nl/tudelft/scrumbledore/KineticsLevelModifierTest.java
Test the Kinetics Level Modifier class. Used Modified Condition Decision Coverage criterium on testing the applyFriction method. Also tested the speed related methods. Finally tested the modify method and the private methods it uses by testing the effect on all different types of Level Elements. Fixed some bugs found during specification based testing.
<testing,bug
=> Test Kinetics Level Modifier

src/test/java/nl/tudelft/scrumbledore/PlayerTest.java
Add a test suite for the Player class, achieving 100% branch and line
coverage.
<testing
=> Test Player

src/test/java/nl/tudelft/scrumbledore/BubbleTest.java
Added Test Suite for the Bubble class.
<testing
=> Test Bubble

src/main/java/nl/tudelft/scrumbledore/BubbleActionsLevelModifier.java, src/main/java/nl/tudelft/scrumbledore/Game.java, src/test/java/nl/tudelft/scrumbledore/BubbleActionsLevelModifierTest.java
Add a test suite for the Bubble Actions Level Modifier class, achieving 100% branch and line coverage.
<testing
=> Test Bubble Actions Level Modifier

src/test/java/nl/tudelft/scrumbledore/PlayerActionsLevelModifierTest.java
Test the functionality of the Player Actions Level Modifier class.
=> Test Player Actions Level Modifier

src/test/java/nl/tudelft/scrumbledore/LevelElementTest.java, src/test/java/nl/tudelft/scrumbledore/LevelTest.java
- Adds new test cases for LevelElement class
- Removes redundant checks in Level test suite
- Removes testAddElementMixed test in Level test suite
=> Extend test suite Level / LevelElement.

src/main/java/nl/tudelft/scrumbledore/Fruit.java, src/test/java/nl/tudelft/scrumbledore/FruitTest.java
- Adds Test suite for Fruit class
- Removes unused time attribute (and related get/set methods) from Fruit class
=> Test fruit

src/test/java/nl/tudelft/scrumbledore/GameTest.java
- Adds test case for the Game::restart method
- The Game::step method cannot be easily tested (without ugly code) due to interaction of six different level modifiers.
=> Adds test for game::restart < organisation

src/main/java/nl/tudelft/scrumbledore/LevelParser.java, src/main/java/nl/tudelft/scrumbledore/NPC.java, src/main/java/nl/tudelft/scrumbledore/NPCLevelModifier.java, src/main/java/nl/tudelft/scrumbledore/SpriteStore.java, src/test/java/nl/tudelft/scrumbledore/LevelParserTest.java
Added several improvements based on FindBugs warnings.
=> Fix findbugs

src/main/java/nl/tudelft/scrumbledore/Constants.java, src/main/java/nl/tudelft/scrumbledore/GUI.java, src/main/java/nl/tudelft/scrumbledore/Logger.java, src/main/java/nl/tudelft/scrumbledore/PlayerActionsLevelModifier.java
Commits fix a number of CheckStyle/PMD violations in the Logger class.
Some warnings require some further discussion regarding design changes and have therefore not yet been resolved.
=> Final checkstyle fix

src/main/java/nl/tudelft/scrumbledore/Logger.java
Refactored the logger spacing and comments as per Aaron's advice.
<organization
=> Refactor Logger Class

.travis.yml
The recent update for Octopull requires subtle updates to the Travis CI
configuration file.
<configuration
=> Add updated travis configuration for Octopull.

src/main/java/nl/tudelft/scrumbledore/BubbleActionsLevelModifier.java
When a Bubbles leaves the level from the top, it is warped and reappears
from the bottom of the level.
<feature
=> Add Bubble warp behavior.

src/test/java/nl/tudelft/scrumbledore/PlatformTest.java
This test suite is designed to cover the Platform class.
<testing
=> Added test suite for the Platform class

src/test/java/nl/tudelft/scrumbledore/ScoreCounterTest.java
Adds a test suite for the ScoreCounter class
<testing
=> Adds a test suite for the ScoreCounter class

src/main/java/nl/tudelft/scrumbledore/LevelParser.java, src/test/java/nl/tudelft/scrumbledore/LevelParserTest.java
- Adds a constructor with path specification possibility
- Adds a test case for the getLevels method
<testing,enhancement
=> Adds a test case for the getLevels method

src/test/java/nl/tudelft/scrumbledore/NPCLevelModifierTest.java
Add a test suite for the NPCLevelModifier class.
<testing
=> Add NPC Level Modifier test suite

src/main/java/nl/tudelft/scrumbledore/Constants.java, src/main/java/nl/tudelft/scrumbledore/GUI.java, src/main/java/nl/tudelft/scrumbledore/Game.java, src/main/java/nl/tudelft/scrumbledore/ScoreCounter.java, src/main/java/nl/tudelft/scrumbledore/StepTimer.java
As per issue #114, I've implemented the display of important values within the GUI.  Also added back-end work for high score functionality and other items.  Also fixed major checkstyle and javadoc issues.
<feature, bug, organization
=> Gui score display

src/main/java/nl/tudelft/scrumbledore/Game.java, src/main/java/nl/tudelft/scrumbledore/ScoreCounter.java, src/test/java/nl/tudelft/scrumbledore/ScoreCounterTest.java
Adds additional test cases to the ScoreCounter class + adds improvements to getScoreString method.
=> Scorecounter test

src/test/java/nl/tudelft/scrumbledore/AnimatedSpriteTest.java, src/test/java/nl/tudelft/scrumbledore/CollisionsLevelModifierTest.java, src/test/java/nl/tudelft/scrumbledore/LevelParserTest.java, src/test/java/nl/tudelft/scrumbledore/StepTimerTest.java
Suppresses and/or fixes several FindBugs/PMD warnings in the test suites.
=> Test cleanup

src/main/java/nl/tudelft/scrumbledore/Game.java, src/main/java/nl/tudelft/scrumbledore/ScoreCounter.java
Replaces new Integer(value).toString() with Integer.toString(value)
<organisation
=> Fixes several FindBugs issues concerning Integer.toString()

src/main/java/nl/tudelft/scrumbledore/Collision.java, src/main/java/nl/tudelft/scrumbledore/CollisionsLevelModifier.java, src/main/java/nl/tudelft/scrumbledore/Game.java, src/main/java/nl/tudelft/scrumbledore/GravityLevelModifier.java, src/main/java/nl/tudelft/scrumbledore/KineticsLevelModifier.java, src/main/java/nl/tudelft/scrumbledore/LevelElement.java, src/main/java/nl/tudelft/scrumbledore/LevelParser.java, src/main/java/nl/tudelft/scrumbledore/Logger.java, src/main/java/nl/tudelft/scrumbledore/Player.java, src/main/java/nl/tudelft/scrumbledore/PlayerActionsLevelModifier.java, src/main/java/nl/tudelft/scrumbledore/Scrumbledore.java
Removed all pointless comments (only in main package) that describe what a
piece of code does, instead of why.
Resolves issue #158.
<documentation
=> Remove pointless comments describing "what".

src/main/java/nl/tudelft/scrumbledore/CollisionsLevelModifier.java, src/main/java/nl/tudelft/scrumbledore/Game.java, src/main/java/nl/tudelft/scrumbledore/KineticsLevelModifier.java, src/main/java/nl/tudelft/scrumbledore/Logger.java, src/main/java/nl/tudelft/scrumbledore/PlayerActionsLevelModifier.java, src/main/java/nl/tudelft/scrumbledore/ScoreCounter.java, src/main/java/nl/tudelft/scrumbledore/Scrumbledore.java, src/main/java/nl/tudelft/scrumbledore/gui/EventListeners.java, src/main/java/nl/tudelft/scrumbledore/gui/GUI.java
Implemented the Singleton Design Pattern in the Logger class. Resolves
issue #160.
<feature,organisation
=> Implement Singleton DP in Logger class.

src/main/java/nl/tudelft/scrumbledore/PlayerActionsLevelModifier.java, src/main/java/nl/tudelft/scrumbledore/gui/GUI.java
Player no longer rendered if the player is dead.
Player actions no longer executed if player is dead. <bug
=> FIX some multiplayer fixes.

src/test/java/nl/tudelft/scrumbledore/CollisionsLevelModifierTest.java
Adds several test cases to the Collisions Level Modifier test suite.
<testing
=> Add several test cases for the Collisions Level Modifier

src/main/java/nl/tudelft/scrumbledore/Logger.java
Updated the Logger class which implements the Singleton design pattern to
be thread safe, using double-checked locking. This was presented during
the lecture as solution 3 to the concurrent instantiation problem.
<bug,organisation
=> Update Logger Singleton to be thread safe.

src/test/java/nl/tudelft/scrumbledore/PlayerActionTest.java
Adds several test cases covering all branches of the invertAction method
<organisation
=> Add test suite for PlayerAction enum

src/main/java/nl/tudelft/scrumbledore/Game.java, src/main/java/nl/tudelft/scrumbledore/GameFactory.java, src/main/java/nl/tudelft/scrumbledore/MultiPlayerGame.java, src/main/java/nl/tudelft/scrumbledore/SinglePlayerGame.java, src/main/java/nl/tudelft/scrumbledore/userinterface/GameDisplay.java, src/main/java/nl/tudelft/scrumbledore/userinterface/Mainmenu.java, src/test/java/nl/tudelft/scrumbledore/GameTest.java, src/test/java/nl/tudelft/scrumbledore/MultiPlayerGameTest.java, src/test/java/nl/tudelft/scrumbledore/SinglePlayerGameTest.java, src/test/java/nl/tudelft/scrumbledore/StepTimerTest.java
Resolves issue #141.
Multiplayer is now an opt-in setting from the main menu. Applied the Factory design pattern to make a distinction between SinglePlayerGame and MultiPlayerGame. Reengineered test suites accordingly.
<feature,organisation,testing
=> SinglePlayer- and MultiPlayerGame Distinction

src/main/java/nl/tudelft/scrumbledore/CollisionsLevelModifier.java, src/main/java/nl/tudelft/scrumbledore/Constants.java, src/main/java/nl/tudelft/scrumbledore/KineticsLevelModifier.java, src/main/java/nl/tudelft/scrumbledore/PlayerActionsLevelModifier.java, src/main/java/nl/tudelft/scrumbledore/ScoreCounter.java, src/main/java/nl/tudelft/scrumbledore/userinterface/LoggingSettings.java
- Suppresses CheckStyle method length warnings
-- Changes protection of changing variables in Constants class
- Adds getters/setters to Constants class
- Should fix all CheckStyle warnings
=> Checkstyle fix

.classpath, src/main/java/nl/tudelft/scrumbledore/Constants.java
Updated the default keybinding and fixed the excessive javafx warnings.
Resolves issue #179.
<user-interface
=> New default keybinding

src/main/resources/css/settingsstyle.css
Fixed the visual bug with the logger settings that only showed one
button.  As Niels found, it's a visual issue with my CSS.
<bug
=> Fix Logger Settings

src/main/java/nl/tudelft/scrumbledore/userinterface/GameDisplay.java
Fixes 4 / 6 of the FindBugs warnings.
Unfortunately the final two warnings could not be suppressed.
<organisation
=> Fixes integer and toString FindBugs warnings

src/main/java/nl/tudelft/scrumbledore/level/PlayerAction.java, src/main/java/nl/tudelft/scrumbledore/level/PlayerActionsLevelModifier.java, src/main/java/nl/tudelft/scrumbledore/userinterface/KeyListeners.java, src/test/java/nl/tudelft/scrumbledore/level/PlayerActionsLevelModifierTest.java
Fixed staircase and movement bugs. The system now processes multiple key presses.
Resolved #182.
<bug,testing,organisation
=> Fix staircase movement

src/main/java/nl/tudelft/scrumbledore/Constants.java, src/main/java/nl/tudelft/scrumbledore/userinterface/GameDisplay.java, src/main/resources/css/victorystyle.css
-Fixed the end screen to fit in with the rest of the GUI.
-Added some nice finisher text to the victory screen.
-Added score and sessions high-score display to the victory screen.
-Added a button that returns to the main menu.
-The victory menu is no modal/in-stage, meaning no settings-like dragability.
<feature
=> Fix end screen

src/main/java/nl/tudelft/scrumbledore/Constants.java, src/main/java/nl/tudelft/scrumbledore/level/PlayerActionsLevelModifier.java
=> Fix bubble shooting

src/main/java/nl/tudelft/scrumbledore/Constants.java, src/main/java/nl/tudelft/scrumbledore/level/Collision.java, src/main/java/nl/tudelft/scrumbledore/level/Fruit.java, src/main/java/nl/tudelft/scrumbledore/level/LevelElement.java, src/main/java/nl/tudelft/scrumbledore/level/NPC.java, src/main/java/nl/tudelft/scrumbledore/level/Platform.java, src/main/java/nl/tudelft/scrumbledore/level/Player.java, src/main/java/nl/tudelft/scrumbledore/level/Vector.java, src/main/java/nl/tudelft/scrumbledore/userinterface/GameDisplay.java, src/main/java/nl/tudelft/scrumbledore/userinterface/MainMenu.java, src/main/java/nl/tudelft/scrumbledore/userinterface/UserInterface.java
Fixes several CheckStyle/FindBugs/PMD warnings and some other remarks from CodePro Analytix.
<organisation
=> Code quality improvement

src/main/java/nl/tudelft/scrumbledore/userinterface/GameDisplay.java
Adds a 4 seconds delay before advancing to a next level to allow a user to get the last bubble.
Reference: #195 
<organisation
=> Adds delay to end of level

src/main/java/nl/tudelft/scrumbledore/level/Level.java, src/main/java/nl/tudelft/scrumbledore/level/LevelParser.java, src/main/java/nl/tudelft/scrumbledore/level/Player.java
Moves the assignment of playerIDs to the LevelParser and removes the total player count as static variable from the Player class
<organisation
=> Fixes Player FindBugs warning

src/main/java/nl/tudelft/scrumbledore/level/CollisionsLevelModifier.java, src/main/java/nl/tudelft/scrumbledore/level/PlayerActionsLevelModifier.java
Fixes the fact that you can fall through bubbles randomly.
Fixes issue #198 
<bug,organisation
=> Fix fall through bubbles

src/main/java/nl/tudelft/scrumbledore/level/GravityLevelModifier.java, src/test/java/nl/tudelft/scrumbledore/level/BubbleActionsLevelModifierTest.java, src/test/java/nl/tudelft/scrumbledore/level/GravityLevelModifierTest.java, src/test/java/nl/tudelft/scrumbledore/level/NPCLevelModifierTest.java, src/test/java/nl/tudelft/scrumbledore/level/PlayerActionsLevelModifierTest.java, src/test/java/nl/tudelft/scrumbledore/level/PlayerTest.java
Adds several new test cases to methods in the scrumbledore.level package for an increased test coverage of at least 90% per class.
<testing
=> scrumbledore.level package test coverage improvement

src/main/java/nl/tudelft/scrumbledore/game/Game.java, src/test/java/nl/tudelft/scrumbledore/game/GameFactoryTest.java, src/test/java/nl/tudelft/scrumbledore/game/GameTest.java, src/test/java/nl/tudelft/scrumbledore/game/ScoreCounterTest.java
Adds several test cases covering methods in the scrumbledore.game package.
<testing
=> Scrumbledore game test extension

src/main/java/nl/tudelft/scrumbledore/Logger.java, src/test/java/nl/tudelft/scrumbledore/ConstantsTest.java, src/test/java/nl/tudelft/scrumbledore/LoggerTest.java
Adds several additional test cases for methods in the scrumbledore package.
No new CheckStyle/FindBugs/PMD issues should be introduced.
<testing
=> Add additional test cases for the scrumbledore package

src/main/java/nl/tudelft/scrumbledore/level/BubbleActionsLevelModifier.java, src/main/java/nl/tudelft/scrumbledore/level/CollisionsLevelModifier.java, src/main/java/nl/tudelft/scrumbledore/level/KineticsLevelModifier.java
Removes the old race condition fix which copied the bubbles into a temporary Array List and now uses an Iterator to walk through the Bubble elements.
Reference: #227 
<organisation
=> Race condition fix refactor

src/test/java/nl/tudelft/scrumbledore/sprite/AnimatedSpriteTest.java, src/test/java/nl/tudelft/scrumbledore/sprite/SpriteTest.java
Adds several test cases for classes in the scrumbledore.sprite package.
<testing
=> Sprite test extension

src/main/java/nl/tudelft/scrumbledore/game/GameFactory.java, src/main/java/nl/tudelft/scrumbledore/game/MultiPlayerGameFactory.java, src/main/java/nl/tudelft/scrumbledore/game/SinglePlayerGameFactory.java, src/main/java/nl/tudelft/scrumbledore/userinterface/GameDisplay.java, src/main/java/nl/tudelft/scrumbledore/userinterface/MainMenu.java, src/test/java/nl/tudelft/scrumbledore/game/GameFactoryTest.java
In the old GameFactory two seperate methods existed that had to be called seperately to instantiate a Single Player or a Multiplayer game. This has now been altered.
<organisation
=> Add GameFactory.makeGame method

src/main/java/nl/tudelft/scrumbledore/Constants.java, src/main/java/nl/tudelft/scrumbledore/level/BasicDynamicElement.java, src/main/java/nl/tudelft/scrumbledore/level/CollisionsLevelModifier.java, src/main/java/nl/tudelft/scrumbledore/level/PlayerActionsLevelModifier.java, src/main/java/nl/tudelft/scrumbledore/powerup/Powerup.java, src/main/java/nl/tudelft/scrumbledore/powerup/PowerupPickUp.java, src/main/java/nl/tudelft/scrumbledore/userinterface/GameDisplay.java, src/main/java/nl/tudelft/scrumbledore/userinterface/KeyListeners.java, src/main/java/nl/tudelft/scrumbledore/userinterface/KeybindingSettings.java, src/test/java/nl/tudelft/scrumbledore/level/CollisionsLevelModifierTest.java
Applies fixes to all CheckStyle and FindBugs warnings that could have been fixed.
PMD warnings have not yet been addressed. (Ask @FlorisXll what to do with them)
<organisation
=> Checkstyle / FindBugs warning fixes

src/main/java/nl/tudelft/scrumbledore/Logger.java, src/test/java/nl/tudelft/scrumbledore/LoggerTest.java
-Implemented additional logger methods that allow fetching of the first and last lines.
-Implement an additional logger method that allows fetching of all the lines.
-Added test cases for the first/last line getters.
-Added a test case for the full getter.
Issue #238
<organisation
=> Add logger linetest

src/main/java/nl/tudelft/scrumbledore/Constants.java, src/main/java/nl/tudelft/scrumbledore/Logger.java, src/main/java/nl/tudelft/scrumbledore/game/GameFactory.java, src/main/java/nl/tudelft/scrumbledore/level/CollisionsLevelModifier.java, src/main/java/nl/tudelft/scrumbledore/level/Fireball.java, src/main/java/nl/tudelft/scrumbledore/level/Level.java, src/main/java/nl/tudelft/scrumbledore/level/Player.java, src/main/java/nl/tudelft/scrumbledore/level/PlayerActionsLevelModifier.java, src/main/java/nl/tudelft/scrumbledore/level/Projectile.java, src/main/java/nl/tudelft/scrumbledore/level/ProjectileActionsLevelModifier.java, src/main/java/nl/tudelft/scrumbledore/powerup/ChiliChicken.java, src/main/java/nl/tudelft/scrumbledore/powerup/TurtleTaco.java, src/main/java/nl/tudelft/scrumbledore/projectile/BlueBubble.java, src/main/java/nl/tudelft/scrumbledore/projectile/Bubble.java, src/main/java/nl/tudelft/scrumbledore/projectile/Fireball.java, src/main/java/nl/tudelft/scrumbledore/projectile/Projectile.java, src/main/java/nl/tudelft/scrumbledore/projectile/ProjectileActionsLevelModifier.java, src/test/java/nl/tudelft/scrumbledore/game/GameFactoryTest.java, src/test/java/nl/tudelft/scrumbledore/level/BubbleActionsLevelModifierTest.java, src/test/java/nl/tudelft/scrumbledore/level/BubbleTest.java, src/test/java/nl/tudelft/scrumbledore/level/CollisionsLevelModifierTest.java, src/test/java/nl/tudelft/scrumbledore/level/KineticsLevelModifierTest.java, src/test/java/nl/tudelft/scrumbledore/level/LevelElementTest.java, src/test/java/nl/tudelft/scrumbledore/level/LevelTest.java
Adds power-up functionality.
All Checkstyle, etc. suggestions that could have been fixed have been fixed.
Issue: #223 
<feature
=> Add power-up functionality

src/main/java/nl/tudelft/scrumbledore/keybinding/Keybinding.java, src/test/java/nl/tudelft/scrumbledore/keybinding/KeybindingTest.java
=> FIX use right iterator.

src/main/java/nl/tudelft/scrumbledore/level/modifier/CollisionsLevelModifier.java, src/main/java/nl/tudelft/scrumbledore/level/modifier/PlayerActionsLevelModifier.java, src/test/java/nl/tudelft/scrumbledore/level/modifier/CollisionsLevelModifierTest.java, src/test/java/nl/tudelft/scrumbledore/level/modifier/NPCLevelModifierTest.java, src/test/java/nl/tudelft/scrumbledore/level/modifier/PlayerActionsLevelModifierTest.java
Also the pickup countdown issue was fixed.
<testing
=> Increased LevelModifier test coverage.

src/main/java/nl/tudelft/scrumbledore/level/element/BasicDynamicElement.java, src/main/java/nl/tudelft/scrumbledore/level/element/BasicStaticElement.java, src/main/java/nl/tudelft/scrumbledore/level/element/Bubble.java, src/main/java/nl/tudelft/scrumbledore/level/element/DynamicElement.java, src/main/java/nl/tudelft/scrumbledore/level/element/Fruit.java, src/main/java/nl/tudelft/scrumbledore/level/element/LevelElement.java, src/main/java/nl/tudelft/scrumbledore/level/element/NPC.java, src/main/java/nl/tudelft/scrumbledore/level/element/Player.java, src/test/java/nl/tudelft/scrumbledore/level/element/BasicDynamicElementTest.java, src/test/java/nl/tudelft/scrumbledore/level/element/BasicStaticElementTest.java, src/test/java/nl/tudelft/scrumbledore/level/element/BubbleTest.java, src/test/java/nl/tudelft/scrumbledore/level/element/FruitTest.java, src/test/java/nl/tudelft/scrumbledore/level/element/LevelElementTest.java, src/test/java/nl/tudelft/scrumbledore/level/element/NPCTest.java, src/test/java/nl/tudelft/scrumbledore/level/element/PlatformTest.java, src/test/java/nl/tudelft/scrumbledore/level/element/PlayerTest.java
Increases the test coverage of the element package to over 90%.
Reference: #268 
<organisation
=> Extend element package test coverage

src/main/java/nl/tudelft/scrumbledore/level/element/PlayerElement.java, src/main/java/nl/tudelft/scrumbledore/level/powerup/ChiliChicken.java, src/main/java/nl/tudelft/scrumbledore/level/powerup/ChiliChickenPickUp.java, src/main/java/nl/tudelft/scrumbledore/level/powerup/TurtleTaco.java, src/main/java/nl/tudelft/scrumbledore/level/powerup/TurtleTacoPickUp.java
Part 2 of JDoc fix
Issue: #275 
<organisation
=> Jdoc fix part 2
